sudo: false
language: php
php:
  - 5.4
before_install:
  - git submodule update --init --recursive
install:
  - composer install
after_success:
  - find . -name "*.git*" | xargs rm -rf
  - rm -rf lib/modules/podlove_web_player/player/podlove-web-player/libs
  - rm -r vendor/bin
  - rm Rakefile
  - rm README.md
  - rm CONTRIBUTING.md
  - find . -name "*composer.json" | xargs rm -rf
  - find . -name "*composer.lock" | xargs rm -rf
  - zip -r latest.zip .
  - curl --ftp-create-dirs -T latest.zip -u $FTP_USER:$FTP_PASSWORD ftp://eric.co.de/files/