sudo: false
language: php
php:
  - 5.4
before_install:
  - git submodule update --init --recursive
install:
  - composer install
after_success:
  - rm -r **/.git
  - rm -r **/.gitignore
  - rm -r **/.gitmodules
  - rm -r lib/modules/podlove_web_player/player/podlove-web-player/libs
  - rm -r vendor/bin
  - rm -r Rakefile
  - rm -r README.md
  - rm -r CONTRIBUTING.md
  - rm -r **/composer.*
  - zip -r latest.zip .
  - curl --ftp-create-dirs -T latest.zip -u $FTP_USER:$FTP_PASSWORD ftp://eric.co.de/files/